steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['-f', 'dock/pom.xml', 'clean', 'package']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/storied-scarab-446316-i2/spring-app:latest', '-f', 'dock/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/storied-scarab-446316-i2/spring-app:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/storied-scarab-446316-i2/react-app:latest', '-f', 'react-app/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/storied-scarab-446316-i2/react-app:latest']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/spring-app-deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster' # Replace with your cluster name
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/react-app-deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster' # Replace with your cluster name

options:
  logging: CLOUD_LOGGING_ONLY

