apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: gcr.io/storied-scarab-446316-i2/react-app:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: gcr-json-key
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: LoadBalancer
  loadBalancerIP: 34.68.248.222 # Replace with the reserved static IP address
  selector:
    app: react-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
