name: Deploy to Render and Netlify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build Spring Boot application
      run: |
        cd dock
        ./mvnw clean install

    - name: Deploy Spring Boot to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST -H "Authorization: Bearer $RENDER_API_KEY" \
        -H "Content-Type: application/json" \
        -d '{"serviceId": "YOUR_RENDER_SERVICE_ID", "clearCache": true}' \
        https://api.render.com/v1/services/YOUR_RENDER_SERVICE_ID/deploys

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build React application
      run: |
        cd react-app
        npm install
        npm run build

    - name: Deploy React to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: |
        npm install -g netlify-cli
        netlify deploy --prod --dir=build --site=$NETLIFY_SITE_ID
